config/routes.rb
Freedom::Application.routes.draw do

  devise_for :users, :path =>'', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  as :user do
    root :to => 'home#index'
  end

  match 'profile' => 'user#profile',            :as => :user_profile
  match 'profile/update/:id' => 'user#update',  :as => :user_update
  match 'admin' => 'admin/dashboard#index',     :as => :admin_dashboard

  match 'home' => 'tracker#index', :as => :home


  %w{users sources articles events webscraper feedbacks classifier}.each do |i|
    match "/admin/#{i}", :to => "admin/#{i}#index", :as => "admin_#{i}"
    match "/admin/#{i}(/:action(/:id))", :to => "admin/#{i}", :action => nil, :id => nil, :format => false, :as => "admin_#{i}_action"
  end


  match 'feedbacks' => 'feedbacks#index', :as => "feedbacks_index"
  match 'feedbacks/(/:action(/:id))' => 'feedbacks', :action=> nil, :id=> nil, :format => false, :as => "feedbacks_action"
  match 'viewArticle', :to => "tracker#viewArticle", :as => "view_article"

  match '/home/viewGraph(/:start/:end)', :to => "tracker#viewGraph", :start => nil, :end => nil, :as => 'view_graph'

  match 'feedbacks/view/:feedback_id/responses/(:action)' => 'responses', :action => nil, :id=> nil, :as => "responses_action"
  match 'admin/feedbacks/view/:feedback_id/responses/(:action)' => 'admin/responses', :action => nil, :id =>nil, :as=> "admin_responses_action"


end

app/controllers/admin/webscraper_controller.rb
class Admin::WebscraperController < ApplicationController
  before_filter :admin_user?
  before_filter :authenticate_user!
  
  def index
    @sources = Source.all
    @classifier = Classifier.all[0].on_off
  end

  def scrape
    id = params[:id]
    source = Source.find_by_id(id)
    
    if not source.scrapable?
      flash[:warning] = "Source #{source.name} was scraped less than 5 minutes ago. Time is #{Time.now}."
    else 
      source.queued = true
      source.save
      source.delay.scrape
      flash[:notice] = "Source #{source.name} is being scrapped. You should see new articles, if any, in a few minutes."
    end
    
    redirect_to admin_webscraper_path
  end
  
  def scrapeAll
    sources = Source.all
    sources.each do |source|
      if source.scrapable?
        source.queued = true
        source.save
        source.delay.scrape
      end
    end
    flash[:notice] = "All sources have been queued to be scraped."
    redirect_to admin_webscraper_path
  end
  
  def accept_reject
    @articles = Article.find(:all, :conditions => {:admin_verified => nil})
    
  end
  
  def accept
    article = Article.find(params[:id])
    article.admin_verified = true
    article.contains_hatespeech = true
    article.save
    flash[:notice] = "Article #{article.id} has been accepted."
    redirect_to admin_webscraper_action_path(:accept_reject)
  end
  
  def reject
    article = Article.find(params[:id])
    article.admin_verified = false
    article.contains_hatespeech = false
    article.save
    flash[:warning] = "Article #{article.id} has been rejected."
    redirect_to admin_webscraper_action_path(:accept_reject)
  end
  
  def update_classifier
    status = params[:status]
    classifier_id = params[:id]
    classifier = Classifier.find(classifier_id)
    classifier.on_off = status == "true"
    classifier.save
  end
  
  def retrain
    Classifier.all[0].delay.retrain
    flash[:notice] = "Classifier is being retrained."
    redirect_to :back
  end

  protected
  def admin_user?
    redirect_to root_path() unless user_signed_in? && current_user.admin?
  end
end

app/helpers/webscraper_helper.rb
module WebscraperHelper
end

app/views/admin/webscraper/accept_reject.html.haml
:javascript
  $(document).ready(function(){
    $(document).on("click", ".open-Article", function () {
      var articleID = $(this).data('article');
      $.ajax({
          type: 'POST',
          url: "#{view_article_path()}",
          data: "articleID=" + articleID,
          success: function(data){
            var article = data[0];
            var links = data[1];
            return_title = article["title"];
            return_text = article["text"];
            return_link = article["link"];
            $('#myModalLabel').text(return_title);
            $('#modalBody').html(return_text);
            $('#modalLink').attr("href", return_link);
            $('#modalHate').attr("href", links["hate"]);
            $('#modalNoHate').attr("href", links["nohate"]);
            $('#modalDelete').attr("href", links["delete"]);
            $('#Article_modal').modal('show');

          },
          error: function(data){
            //alert(data.responseText);
            //$("#bookmarklet_chapter").prepend('<div class="alert-message error"><p>'+data.responseText+'</p></div>');
          }
          });
          
      
     });
     
  });


%div.row-fluid
  %div.span2
    = render 'admin/shared/sidebar'
  %div.span10
    %h2 Articles To Verify

    %table.table.table-striped.table-hover#article_table
      %thead
        %tr
          %th #
          %th Title
          %th Date
          %th Location
          %th Country
          %th Classifier Prediction
          %th 
        %tbody
          - @articles.each do |article|
            %tr
              %td= article.id
              %td{:id => "Article" + article.id.to_s, "data-toggle" => "modal", :href => "#Article", "class" => "open-Article", "data-article" => article.id.to_s}= link_to article.title, "#"
              %td= article.date.strftime('%m/%d/%y')
              -if article.locations[0].nil?
                %td
                %td
              -else
                %td= article.locations[0].name
                %td= article.locations[0].country
              %td= article.contains_hatespeech
              %td
                %div.btn-group
                  = link_to 'Hate', admin_webscraper_action_path(:accept, article.id), :id => "accept_article_#{article.id}", :class => "btn btn-mini"
                  = link_to 'No Hate', admin_webscraper_action_path(:reject, article.id), :id => "reject_article_#{article.id}", :class => "btn btn-mini"
                  = link_to 'Delete', admin_articles_action_path(:delete, article.id), :id => "delete_article_#{article.id}", :class => "btn btn-mini btn-danger"


#Article.modal.hide.fade.in{"aria-hidden" => "true", "aria-labelledby" => "myModalHeader", :role => "dialog", :tabindex => "-1", :id => 'modal'}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}
    %h3#myModalLabel Blank
  .modal-body
    %p#modalBody
      Filler
  .modal-footer
    %div.btn-group.pull-left
      = link_to 'Hate', "#", :id => "modalHate", :class => "btn"
      = link_to 'No Hate', "#", :id => "modalNoHate", :class => "btn"
    %div.btn-group.pull-right
      %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
      = link_to 'Delete', "#", :id => "modalDelete", :class => "btn btn-danger"
      = link_to 'View Original', "#", :class => "btn btn-primary", :id => "modalLink"
      

app/views/admin/webscraper/index.html.haml
:javascript
  $(document).ready(function(){
    setInterval(function() {
      $.ajax({
        type: 'POST',
        url: "#{admin_sources_action_path(:progress)}",
        success: function(data){
          for(key in data) {
            document.getElementById('scrape'+ String(key)).style.width = data[key]['scrape'];
            document.getElementById('content'+ String(key)).style.width = data[key]['content'];
            document.getElementById('classify'+ String(key)).style.width = data[key]['classify'];
            document.getElementById('location'+ String(key)).style.width = data[key]['location'];
            if (data[key]['queued']) {
              document.getElementById('scrape_source_'+ String(key)).className = "btn btn-mini disabled";
            } else {
              document.getElementById('scrape_source_'+ String(key)).className = "btn btn-mini";
            }
          }
        },
        error: function(data){
          //alert(data.responseText);
        }
      });
    }, 5000); //5 seconds
    
    $('#toggle-button').toggleButtons({
      onChange: function ($el, status, e) {
        console.log($el, status, e);
        $.ajax({
          type: 'POST',
          url: "#{admin_webscraper_action_path(:update_classifier, 1)}",
          data: "status=" + String(status),
          success: function(data){
            
          },
          error: function(data){
            //alert(data.responseText);
          }
        });
      },
      style: {
        // Accepted values ["primary", "danger", "info", "success", "warning"] or nothing
        enabled: "success",
        disabled: "danger"
      }
    });
    if(!#{@classifier}) {
      $('#toggle-button').toggleButtons('toggleState'); // to toggle the disabled status
    }
  });
  

%div.row-fluid
  %div.span2
    = render 'admin/shared/sidebar'
    
  %div.span10
    %h2 Web Scraping Controls
    %div
      %span.label.label-info Stage 1: Web Crawling
      %span.label.label-success Stage 2: Content Extraction
      %span.label.label-warning Stage 3: Location Mining
      %span.label.label-important Stage 4: Classification
    %h4 Classifier
    %p Current Accuracy: #{number_to_percentage(Classifier.all[0].accuracy.try(:*,100))}
    %p When off, the web scraper will pull in all articles and you will have to manually determine if article contains hate speech in order to build training data set. When on, the web scraper will attempt to pull in only articles that contain hate speech. You will still need to verify articles but the classifier will be filtering articles it does not think are hate speech.
    %div
      %div.pull-left#toggle-button
        %input{:checked => "", :type => "checkbox"}
      %div.pull-left= button_to 'Retrain', admin_webscraper_action_path(:retrain), :class => "btn btn-danger"
      %div.pull-right= button_to 'Scrape All', admin_webscraper_action_path(:scrapeAll), :class => "btn btn-success"
    
    %table.table.table-striped.table-hover#source_table
      %thead
        %tr
          %th #
          %th Name
          %th Last Scraped
          %th Progress
          %th 
        %tbody
          - @sources.each do |source|
            %tr
              %td= source.id
              %td= link_to source.name, source.home_page
              %td= source.last_scraped
              %td
                .progress.progress-striped.active
                  .bar.bar{:style => "width: " + source.progress_scrape, :id => "scrape" + source.id.to_s}
                  .bar.bar-success{:style => "width: " + source.progress_content, :id => "content" + source.id.to_s}
                  .bar.bar-warning{:style => "width: " + source.progress_location, :id => "location" + source.id.to_s}
                  .bar.bar-danger{:style => "width: " + source.progress_classify, :id => "classify" + source.id.to_s}
              %td 
                - if !source.queued
                  = link_to 'scrape', admin_webscraper_action_path(:scrape, source.id), :id => "scrape_source_#{source.id}", :class => "btn btn-mini"
                - else
                  = link_to 'scrape', admin_webscraper_action_path(:scrape, source.id), :id => "scrape_source_#{source.id}", :class => "btn btn-mini disabled"