config/routes.rb
Freedom::Application.routes.draw do

  devise_for :users, :path =>'', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  as :user do
    root :to => 'home#index'
  end

  match 'profile' => 'user#profile',            :as => :user_profile
  match 'profile/update/:id' => 'user#update',  :as => :user_update
  match 'admin' => 'admin/dashboard#index',     :as => :admin_dashboard

  match 'home' => 'tracker#index', :as => :home


  %w{users sources articles events webscraper feedbacks classifier}.each do |i|
    match "/admin/#{i}", :to => "admin/#{i}#index", :as => "admin_#{i}"
    match "/admin/#{i}(/:action(/:id))", :to => "admin/#{i}", :action => nil, :id => nil, :format => false, :as => "admin_#{i}_action"
  end


  match 'feedbacks' => 'feedbacks#index', :as => "feedbacks_index"
  match 'feedbacks/(/:action(/:id))' => 'feedbacks', :action=> nil, :id=> nil, :format => false, :as => "feedbacks_action"
  match 'viewArticle', :to => "tracker#viewArticle", :as => "view_article"

  match '/home/viewGraph(/:start/:end)', :to => "tracker#viewGraph", :start => nil, :end => nil, :as => 'view_graph'

  match 'feedbacks/view/:feedback_id/responses/(:action)' => 'responses', :action => nil, :id=> nil, :as => "responses_action"
  match 'admin/feedbacks/view/:feedback_id/responses/(:action)' => 'admin/responses', :action => nil, :id =>nil, :as=> "admin_responses_action"


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "carousel"

  def index
    if user_signed_in?
      redirect_to home_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%div#carousel.carousel.slide
  %div.carousel-inner
    %div.active.item
      = image_tag "Space.jpg"
      %div.container
        %div.carousel-caption
          %h1 About The Project
          %p.lead Freedom Tracker is a joint project between Freedom House and UC Berkeley students in the CS169 class that attempts to create a correlation between speech and violent hate events. 
          %a.btn.btn-large.btn-primary{:href => "#learn"} Learn More
    %div.item
      = image_tag "campanile.jpg"
    %div.item
      = image_tag "Africa.jpg"

  %a.carousel-control.left{"data-slide" => "prev", :href => "#carousel"} &lsaquo;
  %a.carousel-control.right{"data-slide" => "next", :href => "#carousel"} &rsaquo;

%div.container.marketing#learn
  %div.row
    %div.span4.center
      = image_tag "BE.jpg", :class => "img-height"
      %h2 UC Berkeley
      %p Berkeley Engineering is a community that is dedicated to creating tomorrow's leaders and supporting today's pioneers. Students and researchers from around the world are drawn to Berkeley by its outstanding reputation, its internationally recognized faculty and its strong tradition of impact in research and teaching.
    %div.span4.center
      = image_tag "freedom_house.png", :class => "img-height"
      %h2 Freedom House
      %p Freedom House is an independent watchdog organization dedicated to the expansion of freedom around the world. Today, as more than two billion people live under oppressive rule, Freedom House speaks out against the main threats to democracy and empowers citizens to exercise their fundamental rights.  
    %div.span4.center
      = image_tag "saas.png", :class => "img-height"
      %h2 CS 169
      %p   CS 169 is the Berkeley software engineering course where students learn ideas and techniques for designing, developing, and modifying large software systems. They also learn about modular design techniques, designing for reuse and maintainability, and project team organization and management.
    
      
      
      
#Signin.modal.hide.fade.in{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => "form-horizontal"}) do |f|
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h3#myModalLabel.center Sign in
    .modal-body.well
      %div.row-fluid
        %div.span10
          .form-inputs  
            = f.input :email, :required => false, :autofocus => true, :input_html => { :class => "span" }
            = f.input :password, :required => false, :input_html => { :class => "span" }    
          .form-buttons
            = f.button :submit, "Sign in"
            = render "devise/shared/links"  
    