config/routes.rb
Freedom::Application.routes.draw do

  devise_for :users, :path =>'', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  as :user do
    root :to => 'home#index'
  end

  match 'profile' => 'user#profile',            :as => :user_profile
  match 'profile/update/:id' => 'user#update',  :as => :user_update
  match 'admin' => 'admin/dashboard#index',     :as => :admin_dashboard

  match 'home' => 'tracker#index', :as => :home


  %w{users sources articles events webscraper feedbacks classifier}.each do |i|
    match "/admin/#{i}", :to => "admin/#{i}#index", :as => "admin_#{i}"
    match "/admin/#{i}(/:action(/:id))", :to => "admin/#{i}", :action => nil, :id => nil, :format => false, :as => "admin_#{i}_action"
  end


  match 'feedbacks' => 'feedbacks#index', :as => "feedbacks_index"
  match 'feedbacks/(/:action(/:id))' => 'feedbacks', :action=> nil, :id=> nil, :format => false, :as => "feedbacks_action"
  match 'viewArticle', :to => "tracker#viewArticle", :as => "view_article"

  match '/home/viewGraph(/:start/:end)', :to => "tracker#viewGraph", :start => nil, :end => nil, :as => 'view_graph'

  match 'feedbacks/view/:feedback_id/responses/(:action)' => 'responses', :action => nil, :id=> nil, :as => "responses_action"
  match 'admin/feedbacks/view/:feedback_id/responses/(:action)' => 'admin/responses', :action => nil, :id =>nil, :as=> "admin_responses_action"


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :sources
  has_many :feedbacks

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :admin

  validates_confirmation_of :password
  validates :first_name, :last_name, :email, :presence => true

  def admin_privileges
    if self.admin
      return "Yes"
    end
    return "No"
  end

  def name
    return self.first_name + " " + self.last_name
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :admin_user?
  before_filter :authenticate_user!

  def index
    @users = User.find(:all, :order => "first_name ASC")
  end

  def edit
    @user = User.find(params[:id])
    @sources = @user.sources
  end

  def update
    @user = User.find(params[:id])
    @user.admin = params[:user][:admin]
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.email = params[:user][:email]
    if @user.save
      flash[:notice] = "Successfully updated user!"
    else
      flash[:warning] = @user.errors.full_messages.join(". ") + "."
    end
    redirect_to admin_users_action_path(:edit, params[:id])
  end

  def new
    userinput = params[:user]

    if userinput
      is_admin = (userinput[:admin] == "true")
      a = User.create(:first_name => userinput[:first_name], :last_name => userinput[:last_name], :email => userinput[:email], :password_confirmation => userinput[:password_confirmation], :password => userinput[:password])
      a.admin = is_admin
      if a.save
        flash[:notice] = "User #{userinput[:first_name]} #{userinput[:last_name]} has been created!"
        redirect_to admin_users_path
      else
        flash[:warning] = a.errors.full_messages.join(". ") + "."
      end
    end
  end

  def delete
    @user = User.find_by_id(params[:id])
    firstname = @user.first_name
    lastname = @user.last_name
    @user.delete
    flash[:notice] = "User #{firstname} #{lastname} has been deleted."
    redirect_to admin_users_path
  end


  protected
  def admin_user?
    redirect_to root_path() unless user_signed_in? && current_user.admin?
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def profile
    @sources = current_user.sources
  end

  def update
    @user = User.find(params[:id])
    if @user.update_with_password(params[:user])
      flash[:notice] = "Successfully updated your information!"
    else
      flash[:warning] = "Invalid input"
    end
    sign_in(@user, :bypass => true)
    redirect_to user_profile_path
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/profile.html.haml
%div.row-fluid
  %div.span3
    %h2 #{current_user.name}
    %ul.thumbnails
      %li.span
        %a.thumbnail{:href => home_path}
          = image_tag 'default_user.png', :class => 'img-circle'
          
  %div.span6.offset3
    %div#card
      %legend.pagination-centered User Properties
      = simple_form_for(current_user, :url => user_update_path(current_user.id), :html => { :method => :put, :class => 'form-horizontal'}) do |f|
        = f.error_notification
        .form-inputs
          = f.input :email, :required => true, :input_html => { :class => "span" }
          = f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false, :input_html => { :class => "span" }
          = f.input :password_confirmation, :required => false, :input_html => { :class => "span" }
          = f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true, :input_html => { :class => "span" }
          %div.btn-group.pull-right
            = f.button :submit, "Update User", :class => "btn-success"
            = f.button :submit, "Delete User", :class => "btn-danger", :value => "Delete User"

  
%div.row-fluid
  %h3 Contributed Sources
  %div#card
    %table.table.table-striped#source_table
      %thead
        %tr
          %th #
          %th Source Name
          %th URL
      %tbody
        -@sources.each do |source|
          %tr
            %td= source.id
            %td= source.name
            %td= source.home_page