config/routes.rb
Freedom::Application.routes.draw do

  devise_for :users, :path =>'', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  as :user do
    root :to => 'home#index'
  end

  match 'profile' => 'user#profile',            :as => :user_profile
  match 'profile/update/:id' => 'user#update',  :as => :user_update
  match 'admin' => 'admin/dashboard#index',     :as => :admin_dashboard

  match 'home' => 'tracker#index', :as => :home


  %w{users sources articles events webscraper feedbacks classifier}.each do |i|
    match "/admin/#{i}", :to => "admin/#{i}#index", :as => "admin_#{i}"
    match "/admin/#{i}(/:action(/:id))", :to => "admin/#{i}", :action => nil, :id => nil, :format => false, :as => "admin_#{i}_action"
  end


  match 'feedbacks' => 'feedbacks#index', :as => "feedbacks_index"
  match 'feedbacks/(/:action(/:id))' => 'feedbacks', :action=> nil, :id=> nil, :format => false, :as => "feedbacks_action"
  match 'viewArticle', :to => "tracker#viewArticle", :as => "view_article"

  match '/home/viewGraph(/:start/:end)', :to => "tracker#viewGraph", :start => nil, :end => nil, :as => 'view_graph'

  match 'feedbacks/view/:feedback_id/responses/(:action)' => 'responses', :action => nil, :id=> nil, :as => "responses_action"
  match 'admin/feedbacks/view/:feedback_id/responses/(:action)' => 'admin/responses', :action => nil, :id =>nil, :as=> "admin_responses_action"


end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
  has_many :responses
  
  attr_accessible :description, :title, :active, :rating, :adminresponse, :last_updated_user, :created_at, :updated_at

  validates :title, :description, :rating, :presence => :true
  validates :rating, :numericality => {:only_integer => :true}

  
  
end

app/controllers/admin/feedbacks_controller.rb
class Admin::FeedbacksController < ApplicationController
  before_filter :admin_user?
  before_filter :authenticate_user!

  def index
  @feedbacks_active = Feedback.find_all_by_active(true)
  @feedbacks_resolved = Feedback.find_all_by_active(false)
  end

  def new
    feedback = params[:feedback]

    if feedback
      f = Feedback.create(:title => feedback[:title], :description => feedback[:description], :rating => feedback[:rating], :active => true)
      f.user = current_user
      f.last_updated_user = current_user.name
      if f.save
        flash[:notice] = "Thank you for submitting website feedback. An admin will respond as soon as possible."
        redirect_to admin_feedbacks_path
      else
        flash[:warning] = f.errors.full_messages.join(". ") + "."
      end
    end
  end

 def edit
   @feedback = Feedback.find_by_id(params[:id])
 end

 def update
   @feedback = Feedback.find_by_id(params[:id])
   @feedback.title = params[:feedback][:title]
   @feedback.description = params[:feedback][:description]
   @feedback.rating = params[:feedback][:rating]
   @feedback.active = params[:feedback][:active]

   if @feedback.save
     flash[:notice] = "Successfully updated feedback form!"
   else
     flash[:warning] = @feedback.errors.full_messages.join(". ")
   end
   redirect_to admin_feedbacks_path
 end



 def resolve
   @feedback = Feedback.find_by_id(params[:id])
   @feedback.active = false
   @feedback.save
   redirect_to admin_feedbacks_path
 end


 def delete
   @feedback = Feedback.find_by_id(params[:id])
   @feedback.delete
   flash[:notice] = "Feedback has been deleted."
   redirect_to admin_feedbacks_path
 end

 def view
  @feedback = Feedback.find_by_id(params[:id])
 end





  protected
  def admin_user?
    redirect_to root_path() unless user_signed_in? && current_user.admin?
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_filter :authenticate_user!
 
  
  def index
  @feedbacks = current_user.feedbacks
  @feedbacks_active = []
  @feedbacks_resolved = []
  @feedbacks.each do |feedback|
    if feedback.active
      @feedbacks_active << feedback
    else 
      @feedbacks_resolved << feedback
    end
  end
  end

  def new
    feedback = params[:feedback]

    if feedback
      f = Feedback.create(:title => feedback[:title], :description => feedback[:description], :rating => feedback[:rating], :active => true)
      f.user = current_user
      f.last_updated_user = current_user.name
      if f.save
        flash[:notice] = "Thank you for submitting website feedback. An admin will respond as soon as possible."
        redirect_to feedbacks_index_path
      else
        flash[:warning] = f.errors.full_messages.join(". ") + "."
      end
    end
  end

 def edit
   @feedback = Feedback.find_by_id(params[:id])
   
 end

 def update
   @feedback = Feedback.find_by_id(params[:id])
   @feedback.title = params[:feedback][:title]
   @feedback.description = params[:feedback][:description]
   @feedback.rating = params[:feedback][:rating]
   @feedback.last_updated_user = current_user.name
   if @feedback.save
     flash[:notice] = "Successfully updated feedback form!"
   else
     flash[:warning] = @feedback.errors.full_messages.join(". ")
   end
   redirect_to feedbacks_index_path
 end
 

 def delete
   @feedback = Feedback.find_by_id(params[:id])
   @feedback.delete
   flash[:notice] = "Feedback deleted."
   redirect_to feedbacks_index_path
 end

 def view 
  @feedback = Feedback.find_by_id(params[:id])
 end



 
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedbacks/edit.html.haml
%div.row-fluid
  %div.span2
    = render 'admin/shared/sidebar'
    
  %div.span5.offset2
    %h2.pagination-centered Edit Feedback Form
    %div#card
      = simple_form_for(@feedback, :url => feedbacks_action_path(:update, @feedback.id), :html => { :method => :put, :class => 'form-horizontal'}) do |f|
        = f.error_notification
        .form-inputs
          = f.input :title, :input_html => { :class => "span"}
          = f.input :description, :as => :text, :input_html => { :class => "span" }
          = f.input :rating, :collection => [0, 1, 2, 3, 4, 5], :input_html => { :class => "span" }
        .form-actions
          %div.btn-group
            = f.button :submit, "Update Feedback Form", :class => "btn-success"
            = link_to 'Cancel', feedbacks_index_path, :class => "btn btn-danger"

app/views/feedbacks/index.html.haml
%div.row-fluid
  %div.span10
    %h2 Feedback
    %div.pull-right= button_to 'Create New Feedback', feedbacks_action_path(:new), :class => "button btn"

    %h3 Active
    %table.table.table-striped.table-hover#article_table
      %thead
        %tr
          %th ID
          %th Title
          %th Author
          %th Rating
          %th Date created
          %th Date last updated
          %th by who?
      %tbody
        - @feedbacks_active.each do |feedback|
          %tr 
            %td= feedback.id
            %td= link_to feedback.title, feedbacks_action_path(:view, feedback.id)
            %td= feedback.user.name
            %td= feedback.rating
            %td= feedback.created_at.strftime('%D %I:%M%p')
            %td= feedback.updated_at.strftime('%D %I:%M%p')
            %td= feedback.last_updated_user
            %td
              = link_to 'Edit', feedbacks_action_path(:edit, feedback.id), :class => "btn btn-mini btn-success"
              = link_to 'Delete', feedbacks_action_path(:delete, feedback.id), :class => "btn btn-mini btn-danger"
    
    %h3 Resolved
    %table.table.table-striped.table-hover#article_table
      %thead
        %tr
          %th ID
          %th Title
          %th Author
          %th Rating
          %th Date created
          %th Date last updated
      %tbody
        - @feedbacks_resolved.each do |feedback|
          %tr 
            %td= feedback.id
            %td= link_to feedback.title, feedbacks_action_path(:view, feedback.id)
            %td= feedback.user.name
            %td= feedback.rating
            %td= feedback.created_at.strftime('%D %I:%M%p')
            %td= feedback.updated_at.strftime('%D %I:%M%p')
            %td
              = link_to 'Delete', feedbacks_action_path(:delete, feedback.id), :class => "btn btn-mini btn-danger"

app/views/feedbacks/new.html.haml
%div.row-fluid
  %div.span1
  %div.span7.offset1
    %h2.pagination-centered Create New Feedback Form
    %div#card
      = simple_form_for(:feedback, :as => :feedback_name, :url => feedbacks_action_path(:new), :html => { :method => :put, :class => 'form-horizontal'}) do |f|
        = f.error_notification
        .form-inputs
          = f.input :title, :input_html => { :class => "span"}
          = f.input :description, :as => :text, :input_html => { :class => "span" }
          = f.input :rating, :collection => [0, 1, 2, 3, 4, 5], :input_html => { :class => "span" }
          %div.btn-group.pull-right
            = f.button :submit, "Create", :class => "btn-success"
            = link_to 'Cancel', feedbacks_index_path, :class => "btn btn-danger"

app/views/feedbacks/view.html.haml
%div.row-fluid
  %div.span1 
  %div.pull-right= button_to 'New Comment', responses_action_path(@feedback.id, :new), :class => "button btn"
  %div.span7.offset1
    %h2 View Feedback Form
    %div#card
      = show_for @feedback do |f|
        = f.attribute :title, :input_html => { :class => "span"}
        = f.association :user, :using => :name, :input_html => { :class => "span"}
        = f.attribute :description, :as => :text, :input_html => { :class => "span" }
        = f.attribute :rating, :as => :integer, :input_html => { :class => "span" }
        = f.attribute :active, :input_html => {:class => "span"}
    %h2 Comments
    -@feedback.responses.each do |response| 
      %div#card
        = show_for response do |r|
          = r.attribute :commenter, :input_html => { :class => "span"}
          = r.attribute :created_at, :input_html => { :class => "span"}
          = r.attribute :body, :as => :text, :input_html => { :class => "span"}
    

 